name: Update Modular Submodule (staging)

on:
  workflow_dispatch:

jobs:
  send_webhook:
    runs-on: ubuntu-latest
    env:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      OWNER: ${{ secrets.OWNER }}
      REPO: ${{ secrets.REPO }}

    steps:
    - name: Send webhook to schedule submodule update on main branch
      run: |
        response=$(curl -s -o response.txt -w "%{http_code}" -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $PERSONAL_ACCESS_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -d '{"ref":"main" "inputs":{"date":"in 1 hour"}}' \
          https://api.github.com/repos/$OWNER/$REPO/actions/workflows/schedule-submodule-update.yml/dispatches)

        # Check the HTTP response code
        if [[ "$response" -ne 204 ]]; then
          echo "Webhook failed with response code $response"
          exit 1  # Fail the job if the response code is not 204
        else
          echo "Webhook triggered successfully!"
        fi

    - name: Send webhook to trigger submodule update on staging
      run: |
        response=$(curl -s -o response.txt -w "%{http_code}" -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $PERSONAL_ACCESS_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -d '{"ref":"staging"}' \
          https://api.github.com/repos/$OWNER/$REPO/actions/workflows/periodic-submodule-update.yml/dispatches)

        # Check the HTTP response code
        if [[ "$response" -ne 204 ]]; then
          echo "Webhook failed with response code $response"
          exit 1  # Fail the job if the response code is not 204
        else
          echo "Webhook triggered successfully!"
        fi

