name: Update Modular Submodule (staging)

on:
  workflow_dispatch:

jobs:
  update-submodule-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: staging

      - name: Set up SSH key for private submodule
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host github.com\n  StrictHostKeyChecking no\n" >> ~/.ssh/config

      - name: Configure Git user
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Update submodule
        run: |
          echo "Submodule to update: $SUBMODULE"
          git submodule init $SUBMODULE
          git submodule update --remote $SUBMODULE
          git add $SUBMODULE
          git commit -m "Updated submodule $SUBMODULE on $(date '+%Y-%m-%d %H:%M:%S')"
          git push origin staging
        env:
          SUBMODULE: "github-api-test"

      - name: Update GitHub Actions Variable
        env:
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          .github/scripts/update_variable.sh $OWNER $REPO $PERSONAL_ACCESS_TOKEN "MODULAR_REQUIRE_UPDATE" "true"
