name: Schedule Update Modular submodule

on:
  schedule:
    - cron: '0 */4 * * *' # Every 4 hours
  workflow_dispatch:
    inputs:
      date:
        description: 'Date to run the workflow'
        required: true
        type: string
        default: 'in 1 hour'

concurrency:
  group: schedule${{ github.event.inputs.date }}
  cancel-in-progress: true

jobs:
  schedule:
    name: Schedule
    runs-on: ubuntu-latest
    steps:
      - uses: austenstone/schedule@v1.3
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          date: ${{ github.event.inputs.date }}
          workflow: 'periodic-submodule-update.yml'
          timezone: 'Europe/Warsaw'
          wait-ms: 45000
