name: Update Submodule

on:
  workflow_dispatch:

jobs:
  update-submodule-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up SSH key for private submodule
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host github.com\n  StrictHostKeyChecking no\n" >> ~/.ssh/config

      - name: Configure Git user
        run: |
          git config --global user.email "github-actions-bot@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"

      - name: Update submodule
        run: |
          echo "Submodule to update: $SUBMODULE"
          git submodule init $SUBMODULE
          git submodule update --remote $SUBMODULE
          git add $SUBMODULE
          git commit -m "Updated submodule $SUBMODULE on $(date '+%Y-%m-%d %H:%M:%S')"
          git push origin main
        env:
          SUBMODULE: "github-api-test"
